[package]
name = "random_nice_emoji"
version = "0.1.0"
authors = ["Max Jacobson <max@hardscrabble.net>"]
description = "This is a little bin which prints a random nice emoji, which I use in my shell prompt"
license = "MIT"

[dependencies]
rand = "0.3.14"
